### ISSUE TITLE
Binaries not found when packaging app as asar archive with Electron

### ISSUE THREAD

**Issue by zs-doron** [Fdawgs/node-poppler#136]
### Describe the bug

I consider this more as a caveat than an actual bug:

When using this library in an app that is packaged as asar archive, e.g. an Electron application packaged with electron-packager, electron-forge or electron-builder, the binaries will not be found when running the installed application.

This is due to `execa` using `child_process.spawn` and not child_process.execFile. Only the latter will cause unpacking the binaries/executing the unpacked binaries, while the first one will try to execute a path like `...\resources\app.asar\node_modules\node-poppler\src\lib\win32\poppler-0.90.1\bin`. This behaviour is described in the [Electron docs](https://www.electronjs.org/docs/tutorial/application-packaging#executing-binaries-inside-asar-archive)

This can be mitigated by setting the popplerPath in the Poppler constructor manually.

### Expected behavior

- Throw a propper error when the binaries are not found
- Add an option to use execFile instead of spawn / migrate to execFile - this could be an option if the actual output is written to a file and not stdout.

### Desktop (please complete the following information)

-   OS: Windows 10 / OSX
-   Node.js Version: 12.16.3

### Additional context

Electron: ^9.0.0 and ^10.0.0

**Comment by Fdawgs** [comment]
Thanks for the comprehensive report @zs-doron, I'll look at tweaking this!

**Comment by Fdawgs** [comment]
Hi @zs-doron , the latest release 1.8.4 should resolve this.
Any extra functionality that `execa` provided over the native `execFile` function was not utilised in this module, so it made sense to have one less external dependency and go back to `execFile`.
