### ISSUE TITLE
Support for Linux/ Ubuntu support without os dependencies  

### ISSUE THREAD

**Issue by ShivaaSezn** [Fdawgs/node-poppler#137]
Please Add support for Linux/Ubuntu os support of pdftotext...&all. This is really in demand and i don't find it anywhere. PDF.js is one alternative but it didn't extracts every text but pdftotext from poppler does. 

Please Please Please add support. The os dependency is a problem because we want to use it in our backend server in firebase functions. which uses ubuntu 18.0.4 LTS and won't allow installing system wide libraries.

Thank you. Hoping a great response.

**Comment by Fdawgs** [comment]
Hi @ShivaaSezn, You're more than welcome to make a pull request with this feature added! I have little Linux experience so would struggle with this.

**Comment by MaXiaoCui11** [comment]
![image](https://user-images.githubusercontent.com/29892162/116171314-190b1d80-a73b-11eb-91a9-a31f1931506e.png)
How to get the page number in a friendly way？
