### ISSUE TITLE
Add ability to read PDF files from stdin

### ISSUE THREAD

**Issue by Fdawgs** [Fdawgs/node-poppler#151]
**Describe the solution you'd like**
Poppler Utils support the ability to read PDF files from stdin for most of the binaries (besides `pdfattach`, `pdfdetach`, `pdfseparate`, `pdfunite`). 

The functionality for this would ideally be reflected in this wrapper module as well.

**Comment by markrummler** [comment]
I know you closed this a few months ago @Fdawgs but it seems there is a pretty easy implementation for a solution over on https://github.com/CodeDaraW/node-pdftocairo/blob/9e35c6d2e66926e870e4dc1240216b8bb449e8a6/src/index.ts#L170

I'd take a crack at a PR if you're interested but TS definitions are out of my wheelhouse.

**Comment by Fdawgs** [comment]
Brilliant, thanks @markrummler!
If you're willing to give it a shot that'd be great.
