### ISSUE TITLE
Poppler win32 binaries is missing language pack

### ISSUE THREAD

**Issue by secrecysiu** [Fdawgs/node-poppler#171]
pdftocairo convert to image some characters can not be display as below error message

> Missing language pack for 'Adobe-GB1' mapping
> Missing language pack for 'Adobe-CNS1' mapping
> No font in show

Suggest to build win 32 poppler with poppler-data

below win32 build is included Poppler-data for your reference
https://tm23forest.com/contents/poppler-for-windows

Without poppler-data.
$ pdfinfo -listenc

> Available encodings are:
> ASCII7
> Latin1
> Symbol
> UTF-16
> UTF-8
> ZapfDingbats

With poppler-data.
$ pdfinfo -listenc

> Available encodings are:
> ASCII7
> Big5
> Big5ascii
> EUC-CN
> EUC-JP
> GBK
> ISO-2022-CN
> ISO-2022-JP
> ISO-2022-KR
> ISO-8859-6
> ISO-8859-7
> ISO-8859-8
> ISO-8859-9
> KOI8-R
> Latin1
> Latin2
> Shift-JIS
> Symbol
> TIS-620
> UTF-16
> UTF-8
> Windows-1255
> ZapfDingbats

**Comment by Fdawgs** [comment]
Thanks for reporting this @secrecysiu, I'll investigate!

**Comment by secrecysiu** [comment]
https://github.com/oschwartz10612/poppler-windows/releases/tag/v20.12.1-data

poplar-windows is released with data version, please include in your package

**Comment by Fdawgs** [comment]
Hi @secrecysiu  sorry for the delay!
I am awaiting v21.01 to be released (or v21.02 at this rate) so i can kill two birds with one stone.

**Comment by Fdawgs** [comment]
@secrecysiu this has been resolved in the latest version. 😄
