### ISSUE TITLE
error dyld: Library not loaded: @rpath/libpoppler.100.dylib

### ISSUE THREAD

**Issue by JLWolff** [Fdawgs/node-poppler#202]
### Describe the bug

When i try to run the NodeJs code with the node-poppler lib i have the 
"Library not loaded: @rpath/libpoppler.100.dylib" error. As can be seen in the printscreen below

### To Reproduce

i have this simple function for converting pdf to jpg,just like one of the examples in the page of the lib, when ran in macOS had the error
    
### Expected behavior

It was expected to convert the files as normal and as it happens in my Windows system too.

### Screenshots

![image](https://user-images.githubusercontent.com/37195843/108438881-0f9b9b80-7248-11eb-81bc-fcfb84ba4c2c.png)

### Desktop (please complete the following information)

-   Mac OS 10.13
-   Node.js Version 12.16

**Comment by Fdawgs** [comment]
Thanks @JLWolff, i'll take a look!

**Comment by JLWolff** [comment]
Ok, @Fdawgs thanks! If you need any more info just let me know. Im using the latest version of the node-poppler too.

**Comment by Fdawgs** [comment]
Hi @JLWolff, as I'm using Windows and don't have access to a Mac I can't test this myself. 

Does this also occur if you pass in a separately downloaded version of Poppler (as documented in the [Linux and macOS/Darwin Support](https://github.com/Fdawgs/node-poppler#linux-and-macosdarwin-support) section of the readme) or is it just with the included macOS binaries?

**Comment by JLWolff** [comment]
Hey, @Fdawgs it worked with the binaries downloaded externally. So it just occur with the included ones.

**Comment by Fdawgs** [comment]
Hi @JLWolff, the contributor who helped add the included macOS binaries is no longer on GitHub. 😞

Unless you're able to make a pull request to add new, working macOS binaries and libs, I may have to remove them.
I don't have any macOS experience to keep them up to date myself, and it seems that homebrew is the way to go on the Mac side.

**Comment by JLWolff** [comment]
Ok, @Fdawgs , i don't have much experience in the macOS side too, i am actually doing this for someone and using a VM for the mac part!! lol

But i can try to do this pull request of the updated macOS binaries, sure. i transfered them to my Win already and will do this asap.

**Comment by siuying** [comment]
Hi,

I hit the problem and able to solve it by:

0. go to lib folder `/node_modules/node-poppler/src/lib/darwin/poppler-0.89.0/lib`
1. remove libpoppler.100.dylib `rm libpoppler.100.dylib`
2. soft link libpoppler.100.0.0.dylib `ln -s libpoppler.100.0.0.dylib libpoppler.100.dylib`

I don't sure why the symbolic link is broken ... but by recreate it it work for me.

**Comment by JLWolff** [comment]
Hello @siuying, at the time i needed the poppler files to be portable so i ended up saving it locally and linking all libs correctly with the path of the project.

Anyways, thanks for the solve. :)

**Comment by mcdado** [comment]
Also, when installing with npm the executables in `node_modules/node-poppler/src/lib/darwin/poppler-0.89.0/bin` do not have executable permissions:

```
~/Desktop/test ❯ ls -la node_modules/node-poppler/src/lib/darwin/poppler-0.89.0/bin
total 1176
drwxr-xr-x  14 David  staff   448B Aug 31 12:45 .
drwxr-xr-x  14 David  staff   448B Aug 31 12:45 ..
-rw-r--r--   1 David  staff    19K Aug 31 12:45 pdfattach
-rw-r--r--   1 David  staff    20K Aug 31 12:45 pdfdetach
-rw-r--r--   1 David  staff    19K Aug 31 12:45 pdffonts
-rw-r--r--   1 David  staff    45K Aug 31 12:45 pdfimages
-rw-r--r--   1 David  staff    56K Aug 31 12:45 pdfinfo
-rw-r--r--   1 David  staff    19K Aug 31 12:45 pdfseparate
-rw-r--r--   1 David  staff   140K Aug 31 12:45 pdftocairo
-rw-r--r--   1 David  staff    97K Aug 31 12:45 pdftohtml
-rw-r--r--   1 David  staff    26K Aug 31 12:45 pdftoppm
-rw-r--r--   1 David  staff    26K Aug 31 12:45 pdftops
-rw-r--r--   1 David  staff    53K Aug 31 12:45 pdftotext
-rw-r--r--   1 David  staff    37K Aug 31 12:45 pdfunite
```

This causes errors when calling the pdfToCairo methods. Also, while poppler is included (albeit an older version) cairo is not... in my opinion would be better to no include the library and just leave the instructions on how to install poppler and cairo from Homebrew.

**Comment by Fdawgs** [comment]
Cheers @mcdado, I end up using the home brew version myself.

As alluded too earlier in this issue, I don't have the know how to maintain the MacOS binaries.
I will remove them either this week or next (at the same time as updating the Windows binaries to 21.09.0).
