### ISSUE TITLE
How to get the page number in a friendly way

### ISSUE THREAD

**Issue by MaXiaoCui11** [Fdawgs/node-poppler#248]
![image](https://user-images.githubusercontent.com/29892162/116171602-a9496280-a73b-11eb-835c-e3bee9ec5826.png)
**This is the data obtained by pdfInfo function. Can this data be directly processed into JSON and returned?**

**Comment by Fdawgs** [comment]
Hi @MaXiaoCui11, that sounds like a great idea! I will investigate how easy this is to do.

**Comment by sainf** [comment]
A json flag it would be nice!

My approach :

```javascript
const camelCase = require('camelcase')

const ret = await poppler.pdfInfo(path.resolve('myPdf.pdf''))
const info = {}
ret.split('\n').map(r => r.split(': ')).forEach(r => {
  if (r.length > 1) info[camelCase(r[0])] = r[1].trim()
})
```

![image](https://user-images.githubusercontent.com/1210947/119143973-236dbe00-ba40-11eb-87d0-28a36b0178de.png)

**Comment by Fdawgs** [comment]
@MaXiaoCui11 see #268, shamelessly stole @sainf's solution.

@sainf are you happy for me to credit you in an in-line comment, and in the changelog?

**Comment by sainf** [comment]
Happy to be part on an solution! Thanks for the comment!
