### ISSUE TITLE
Problem with encoding when returning buffer instead of output file

### ISSUE THREAD

**Issue by mcdado** [Fdawgs/node-poppler#256]
Hello, if I choose not to save to file directly, but rather get the output to a buffer to do whatever I need to do with it, it seems that the returned buffer is corrupted.

```js
const pdfBuffer = await fs.promises.readFile(inputPdfFile)
const result = await poppler.pdfToCairo(pdfBuffer, null, { singleFile: true, pngFile: true }) // jpg too!
const pngBuffer = Buffer.from(result, 'utf-8') // this buffer is always broken
await fs.promises.writeFile(outputPath, pngBuffer);
```

I tried setting the encoding of `Buffer.from()` to binary as well, but when the file is saved it is always broken. From a quick look at the code it seems that the problem comes from the fact that the png contents are converted to utf-8 on the way... one clue about this is that SVG output works, because SVG is a text-based format, while PNG (and JPEG, for that matter) is a binary format, and they get corrupted.

https://github.com/Fdawgs/node-poppler/blob/3cfb17b16c369462f2bff239d23e374fb0cc4fa0/src/index.js#L749-L753

**Comment by Fdawgs** [comment]
Thanks for reporting this @mcdado!

I'll look at removing the default encoding.

**Comment by Fdawgs** [comment]
@mcdado, I've removed this in `v3.0.1` 😁

**Comment by cepm-nate** [comment]
Node-Poppler 5.0.2, running on Node on Windows Server 2019. is there any other debug info that might help?

**Comment by Fdawgs** [comment]
I'll take a look tomorrow @cepm-nate, if you can share the pdf as well that'd be fab!

**Comment by cepm-nate** [comment]
Sure thing! https://www.jetdrop.net/F58yl3mvCg9#CwDgNAjA7FYEzUgVjpUYlLANgMwfAgE585ds0IwRSAGCiJUhSbIgfTgCcBjADQDiRCFz4AFAM4QAKgA8kAMQAiAZWwAZAPZ91uYAAcASgHNuXAEZA (link good till Nov 5th)
