### ISSUE TITLE
i instaleed this pakage and get errore. Error: spawn ./usr/bin/pdftocairo ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19) "os:centos8,node-poppler version4.1.1

### ISSUE THREAD

**Issue by elm2013** [Fdawgs/node-poppler#291]

**Comment by Fdawgs** [comment]
Hi @elm2013, have you followed the steps regarding usage with Linux operating systems, [found here](https://github.com/Fdawgs/node-poppler#linux-and-macosdarwin-support)?
The ENOENT error indicates that the binary doesn't exist.
