### ISSUE TITLE
Does poppler.pdfToCairo accepts input like blob Urls, or anything other than pdf file and pdf url?

### ISSUE THREAD

**Issue by Srimathi-kec** [Fdawgs/node-poppler#359]
Need to know if poppler library accepts Blob Url or base64 or arraybuffer or file object as a input and convert it to image file.
When I try to use blob url I am getting below error.

![bloburl](https://user-images.githubusercontent.com/26833206/142998078-18550a32-26cd-4cfd-ba2e-98a40c4a1d65.PNG)

Please let me know what are the possible formats in which we can give the input pdf file.

**Comment by Fdawgs** [comment]
Hi @Srimathi-kec, `poppler.pdfToCairo()` only accepts a String containing the PDF file path, or Buffer in the file param, see the [API documentation here](https://github.com/Fdawgs/node-poppler/blob/master/API.md#popplerpdftocairofile-outputfile-options--promisestringerror).

Adding support for those additional input types sounds interesting though!

**Comment by Srimathi-kec** [comment]
Hi @Fdawgs , Can you please explain how the input buffer structure should be? 
I am using buffer format like below, but it is not accepted by the library.
![image](https://user-images.githubusercontent.com/26833206/143199233-049b09cf-a653-47eb-9921-cd4da89b005c.png)

**Comment by Srimathi-kec** [comment]
Hi @Fdawgs , Also when I directly give the buffer object without using stringify, I am getting below error.
Please let me know what format of buffer is expected by pdfToCairo.
![image](https://user-images.githubusercontent.com/26833206/143200267-d0c7272e-e3f4-4263-8be1-f011f092f5aa.png)

**Comment by Fdawgs** [comment]
As an example:

```js
const poppler = new Poppler();
const file = './path/example.pdf';

// attachmentFile will be a Buffer
const attachmentFile = await fs.readFile(file);
const options = {
    jpegFile: true,
};
const outputPathPattern = `./path/example-jpg-`;

const res = await poppler.pdfToCairo(
    attachmentFile,
    outputPathPattern,
    options
);


```

**Comment by Srimathi-kec** [comment]
Hi @Fdawgs , Here what I have is blob object of the file and not the actual pdf file. Is there anything that could convert the blob object to buffer readable by the library? Below code is not working
console.log("fileobj", req.body);
    var fileObj = req.body;
    var filepath = fileObj['data'];
    console.log("filepat",filepath)
    const buffer=new Buffer(JSON.stringify(filepath));
    console.log("buffer:",buffer)
    const pdfBuffer = await fs.promises.readFile(buffer)
    console.log(pdfBuffer)
resp = await poppler.pdfToCairo(pdfBuffer, outputFile, options);

**Comment by Fdawgs** [comment]
This is out of scope of this package, sorry. You will probably need something like Axios to read it, then transform into a Buffer, then pass to this.
