### ISSUE TITLE
Poppler library not supported in Linux

### ISSUE THREAD

**Issue by Srimathi-kec** [Fdawgs/node-poppler#362]
When I run the application in windows, its working as expected.(pdf to image conversion using poppler.pdftocairo)
When the application is deployed in linux environment, pdf to image conversion is not working.
I am getting below error. Please let me know, how to fix. If there is any package need to be added, please share the procedure.
![image](https://user-images.githubusercontent.com/26833206/144013037-8925b7c6-4183-42d3-8cf0-27551afab8d3.png)

**Comment by Fdawgs** [comment]
Hi @Srimathi-kec, see the [Linux and macOS/Darwin Support](https://github.com/Fdawgs/node-poppler#linux-and-macosdarwin-support) section in the docs.
