### ISSUE TITLE
pdfToCairo result "Couldn't open 'nameToUnicode' file"

### ISSUE THREAD

**Issue by lling1105** [Fdawgs/node-poppler#439]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

- [X] I agree to follow the [Code of Conduct](../../CODE_OF_CONDUCT.md) that this project adheres to

### API/app/plugin version

22.04.0

### Node.js version

14.18

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

21H2

### Description

convert pdf file to jpg files but encounter following error
```js
I/O Error: Couldn't open 'nameToUnicode' file 'node_modules\node-poppler\src\lib\win32\poppler-22.04.0\share\poppler\nameToUnicode\Bulgarian'
I/O Error: Couldn't open 'nameToUnicode' file 'node_modules\node-poppler\src\lib\win32\poppler-22.04.0\share\poppler\nameToUnicode\Greek'
I/O Error: Couldn't open 'nameToUnicode' file 'node_modules\node-poppler\src\lib\win32\poppler-22.04.0\share\poppler\nameToUnicode\Thai'
```

### Steps to Reproduce

```js
const _opts = {
        scalePageTo:3072,
        jpegFile:true
    };
poppler.pdfToCairo(pdfFilePath,undefined, _opts)
            .then(res => {
               ...
            })
            .catch(error => {
                console.error(error);
                reject(error);
            })
```

### Expected Behaviour

should result with jpg files

**Comment by Fdawgs** [comment]
Hi there, I am unable to reproduce this, are you able to provide a file?
