### ISSUE TITLE
I think you might want /usr/bin in place of ./usr/bin in the docs

### ISSUE THREAD

**Issue by testlabauto** [Fdawgs/node-poppler#462]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

- [X] I agree to follow the [Code of Conduct](../../CODE_OF_CONDUCT.md) that this project adheres to

### Node.js version

16.16.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu

### Description

Just a heads up... I spent some time debugging and feel like the docs should say
```
/usr/bin
```
in place of 
```
./usr/bin
```
At least that is what I needed to get it to work, but I am no Linux expert :)
Cheers

### Steps to Reproduce

Just a documentation note.

**Comment by Fdawgs** [comment]
Thanks @testlabauto, had it right in the test scripts 😄
