### ISSUE TITLE
Update OSX Poppler binaries to 0.87.0

### ISSUE THREAD

**Issue by Fdawgs** [Fdawgs/node-poppler#47]

**Comment by chetanism** [comment]
Hi,
I have raised a PR to update OSX Poppler binaries to 0.89.0: #97 .

Thanks

**Comment by Fdawgs** [comment]
Resolved by pull request #97

**Comment by adityapatadia** [comment]
This gives error `dyld: Library not loaded: @rpath/libpoppler.100.dylib`.

**Comment by Fdawgs** [comment]
Hi @adityapatadia, could you please open a separate issue detailing when/how you are occuring this error? Thanks!
