### ISSUE TITLE
want to use popler by importing it with wasm

### ISSUE THREAD

**Issue by tianmuji** [Fdawgs/node-poppler#522]
### Prerequisites

- [X] I have written a descriptive title
- [X] I have searched existing feature requests to ensure it has not already been proposed

- [X] I agree to follow the [Code of Conduct](../../CODE_OF_CONDUCT.md) that this project adheres to

### Description

Poppler provide C++ api for pdf manipulation
I can write some wrapper function to export these apis
and I can export it into wasm using emscripten

if there is existing wasm package, I hope to use it directly.
Otherewise, I can submit a PR

**Comment by Fdawgs** [comment]
Thanks @tianmuji, this repo is just a simple wrapper around the binaries but happy to accept any extensions to it where the binaries no longer need to be provided!

**Comment by BernhardBehrendt** [comment]
That would be amazingly great @tianmuji  as the whole package could then ship poppler also for linux and mac computers without the need of installing the dependency.

**Comment by msageryd** [comment]
My two cents:

This would be really cool, but I'm a bit wary.
- Maintenance on this currently clean and neat library would possibly skyrocket.
- I got the impression that WASM might slow things down compared to natively compiled code
- If anything I would like this library to lessen by lgetting rid of the Windows binaries and put those in an optional dependency.

@tianmuji You seem confident in WASM-wrapping. Could this be done as an optional dependency so it wouldn't bother the current code base much?

An alternative for you might be this: https://github.com/hyzyla/pdfium

I need as speedy conversion as possible, so I'm staying with a wrapped command-line Poppler. 
Also see: https://github.com/hyzyla/pdfium/issues/4#issuecomment-1724312484

**Comment by Fdawgs** [comment]
On reflection, whilst this is great it is outside the scope of this module, which is to be a simple wrapper.
